### PR TITLE
Amazon porting

### PR DESCRIPTION
**Pull request by firekesti**
Reverts the main release branch back down to 1.5.11, which is what Amazon's latest 1.x is based on.
Then, applies all Amazon-specific changes.

FYI @mitsnosrap - and I think I'll leave amazon-porting as the main branch for this set of shenanigans, this PR is for informative/record-keeping purposes only...?

### CODE REVIEW

**Comment by firekesti** [comment]
Although, the Brightcove fork is based off 1.5.13, so I might have to undo the reversions to get this branch back up to being a reasonable base to get the Brightcove changes merged in.

**Comment by elsnosrap** [comment]
Good luck.

**Comment by elsnosrap** [comment]
awh, I miss getting GitHub emails from Kate! 😢

**Comment by backer** [comment]
lol same, I was so confused by this notification

**Pull request closed without merging**
